name             'test-tdi'
maintainer       'YOUR_NAME'
maintainer_email 'YOUR_EMAIL'
license          'All rights reserved'
description      'Installs/Configures test-tdi'
long_description 'Installs/Configures test-tdi'
version          '0.1.0'
